version: "2"

checks:
  file-lines:
    enabled: false

plugins:
  pep8:
    enabled: true

exclude_patterns:
- "**/tests/"
- "**/migrations/"
- "**/fixtures/"
- "**/static/"
- "settings.py"
- "__init__.py"
