# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-23 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_alerte', models.DateField(blank=True, null=True, verbose_name='Date alerte')),
                ('etat', models.CharField(choices=[('A_VERIFIER', 'A vérifier'), ('VERIFIER', 'Vérifier'), ('COURRIER', 'Courrier à préparer')], default='A_VERIFIER', max_length=10, verbose_name='Etat')),
            ],
            options={
                'ordering': ['date_alerte'],
            },
        ),
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Banque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('rue', models.CharField(blank=True, max_length=200, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('boite', models.CharField(blank=True, max_length=10, null=True)),
                ('lieu_dit', models.CharField(blank=True, max_length=200, null=True)),
                ('superficie', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('performance_energetique', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'ordering': ['localite', 'rue'],
            },
        ),
        migrations.CreateModel(
            name='ContratGestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('montant_mensuel', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Batiment')),
            ],
        ),
        migrations.CreateModel(
            name='ContratLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date début')),
                ('date_fin', models.DateField()),
                ('renonciation', models.DateField(blank=True, null=True)),
                ('remarque', models.TextField(blank=True, null=True)),
                ('loyer_base', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('charges_base', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('assurance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Assurance')),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Batiment')),
            ],
            options={
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='FinancementLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date début')),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('loyer', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('charges', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('index', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('contrat_location', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.ContratLocation')),
            ],
        ),
        migrations.CreateModel(
            name='FraisMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_realisation', models.DateField(blank=True, null=True, verbose_name='Date réalisation')),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Batiment', verbose_name='Batiment')),
            ],
        ),
        migrations.CreateModel(
            name='Honoraire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField(blank=True, null=True, verbose_name='Date paiement')),
                ('etat', models.CharField(choices=[('A_VERIFIER', 'A vérifier'), ('IMPAYE', 'Impayé'), ('EN_RETARD', 'En retard'), ('PAYE', 'Payé')], default='A_VERIFIER', max_length=10, verbose_name='Etat')),
                ('contrat_gestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ContratGestion', verbose_name='Contrat de gestion')),
            ],
        ),
        migrations.CreateModel(
            name='Localite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_postal', models.CharField(max_length=10)),
                ('localite', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['localite'],
            },
        ),
        migrations.CreateModel(
            name='Locataire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infos_complement', models.TextField(blank=True, null=True)),
                ('principal', models.BooleanField(default=True)),
                ('societe', models.CharField(blank=True, max_length=100, null=True, verbose_name='Société')),
                ('tva', models.CharField(blank=True, max_length=30, null=True)),
                ('profession', models.CharField(blank=True, max_length=50, null=True)),
                ('civilite', models.CharField(choices=[('NON_PRECISE', '-'), ('MADAME', 'Madame'), ('MONSIEUR', 'Monsieur'), ('MAITRE', 'Maitre'), ('DOCTEUR', 'Docteur')], default='NON_PRECISE', max_length=15)),
                ('contrat_location', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.ContratLocation')),
            ],
        ),
        migrations.CreateModel(
            name='ModeleDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(max_length=50)),
                ('contenu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=100, null=True)),
                ('pays_naissance', models.CharField(blank=True, max_length=100, null=True)),
                ('num_identite', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('gsm', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='photos')),
                ('texte', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date début')),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Batiment')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Personne', verbose_name='Propriétaire')),
            ],
        ),
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('rue', models.CharField(blank=True, max_length=200, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('boite', models.CharField(blank=True, max_length=10, null=True)),
                ('lieu_dit', models.CharField(blank=True, max_length=200, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('localite', models.CharField(blank=True, max_length=150, null=True)),
                ('personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Personne')),
            ],
        ),
        migrations.CreateModel(
            name='SuiviLoyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField()),
                ('etat_suivi', models.CharField(choices=[('A_VERIFIER', 'A vérifier'), ('IMPAYE', 'Impayé'), ('EN_RETARD', 'En retard'), ('PAYE', 'Payé')], default='A_VERIFIER', max_length=10)),
                ('remarque', models.TextField(blank=True, null=True)),
                ('loyer_percu', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('charges_percu', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('financement_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.FinancementLocation')),
            ],
            options={
                'ordering': ['date_paiement'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='personne',
            unique_together=set([('nom', 'prenom')]),
        ),
        migrations.AddField(
            model_name='locataire',
            name='personne',
            field=models.ForeignKey(error_messages={'unique': 'Please enter your name'}, on_delete=django.db.models.deletion.CASCADE, to='main.Personne'),
        ),
        migrations.AddField(
            model_name='fraismaintenance',
            name='entrepreneur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Personne'),
        ),
        migrations.AddField(
            model_name='fraismaintenance',
            name='societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Societe'),
        ),
        migrations.AddField(
            model_name='contratgestion',
            name='gestionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Personne'),
        ),
        migrations.AddField(
            model_name='batiment',
            name='localite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Localite'),
        ),
        migrations.AddField(
            model_name='alerte',
            name='contratGestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ContratGestion', verbose_name='Contrat de gestion'),
        ),
        migrations.AddField(
            model_name='alerte',
            name='contratLocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ContratLocation', verbose_name='Contrat location'),
        ),
        migrations.AlterUniqueTogether(
            name='proprietaire',
            unique_together=set([('proprietaire', 'batiment')]),
        ),
        migrations.AlterUniqueTogether(
            name='locataire',
            unique_together=set([('personne', 'contrat_location')]),
        ),
    ]
