# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-04 09:56
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_alerte', models.DateField(blank=True, null=True, verbose_name='Date alerte')),
                ('etat', models.CharField(choices=[('A_VERIFIER', 'A vérifier'), ('VERIFIER', 'Vérifier'), ('COURRIER', 'Courrier à préparer')], default='A_VERIFIER', max_length=10, verbose_name='Etat')),
            ],
            options={
                'ordering': ['date_alerte'],
            },
        ),
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Banque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('rue', models.CharField(blank=True, max_length=200, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('boite', models.CharField(blank=True, max_length=10, null=True)),
                ('lieu_dit', models.CharField(blank=True, max_length=200, null=True)),
                ('superficie', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('performance_energetique', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'ordering': ['localite', 'rue'],
            },
        ),
        migrations.CreateModel(
            name='ContratGestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('montant_mensuel', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Batiment')),
            ],
        ),
        migrations.CreateModel(
            name='ContratLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date début')),
                ('date_fin', models.DateField()),
                ('renonciation', models.DateField(blank=True, null=True)),
                ('remarque', models.TextField(blank=True, null=True)),
                ('loyer_base', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('charges_base', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('assurance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Assurance')),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Batiment')),
            ],
            options={
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='DocumentModele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('contenu', ckeditor.fields.RichTextField()),
                ('sujet', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancementLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date début')),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('loyer', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('charges', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('index', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('contrat_location', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.ContratLocation')),
            ],
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fonction', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FraisMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_realisation', models.DateField(blank=True, null=True, verbose_name='Date réalisation')),
                ('batiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Batiment', verbose_name='Batiment')),
                ('contrat_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ContratLocation')),
            ],
        ),
        migrations.CreateModel(
            name='Honoraire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField(blank=True, null=True, verbose_name='Date paiement')),
                ('etat', models.CharField(choices=[('A_VERIFIER', 'A vérifier'), ('IMPAYE', 'Impayé'), ('EN_RETARD', 'En retard'), ('PAYE', 'Payé')], default='A_VERIFIER', max_length=10, verbose_name='Etat')),
                ('contrat_gestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ContratGestion', verbose_name='Contrat de gestion')),
            ],
        ),
        migrations.CreateModel(
            name='IndiceSante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_calcul', models.DateField()),
                ('annee_base', models.IntegerField()),
                ('indice', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Localite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_postal', models.CharField(max_length=10)),
                ('localite', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['localite'],
            },
        ),
        migrations.CreateModel(
            name='Locataire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infos_complement', models.TextField(blank=True, null=True)),
                ('principal', models.BooleanField(default=True)),
                ('tva', models.CharField(blank=True, max_length=30, null=True)),
                ('civilite', models.CharField(choices=[('NON_PRECISE', '-'), ('MADAME', 'Madame'), ('MADEMOISELLE', 'Mademoiselle'), ('MONSIEUR', 'Monsieur'), ('MAITRE', 'Maitre'), ('DOCTEUR', 'Docteur')], default='NON_PRECISE', max_length=15)),
                ('actif', models.BooleanField(default=True)),
                ('contrat_location', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.ContratLocation')),
            ],
        ),
        migrations.CreateModel(
            name='ModeleDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('type_document', models.CharField(blank=True, max_length=50, null=True)),
                ('contenu', ckeditor.fields.RichTextField()),
                ('sujet', models.CharField(blank=True, max_length=255, null=True)),
                ('fichier_modele', models.CharField(blank=True, max_length=255, null=True)),
                ('modele', models.FileField(blank=True, null=True, upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('prenom2', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=100, null=True)),
                ('num_identite', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('gsm', models.CharField(blank=True, max_length=30, null=True)),
                ('num_compte_banque', models.CharField(blank=True, max_length=30, null=True)),
                ('titre', models.CharField(blank=True, choices=[('NON_PRECISE', 'Madame, Monsieur,'), ('MONSIEUR', 'Monsieur'), ('MADAME', 'Madame'), ('MADEMOISELLE', 'Mademoiselle'), ('MAITRE', 'Maître')], default='NON_PRECISE', max_length=20, null=True)),
                ('fonction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Fonction')),
                ('pays_naissance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Pays')),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='photos')),
                ('texte', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Professionnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('fonction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Fonction')),
                ('personne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Personne')),
            ],
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date début')),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Batiment')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Personne', verbose_name='Propriétaire')),
            ],
        ),
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('rue', models.CharField(blank=True, max_length=200, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('boite', models.CharField(blank=True, max_length=10, null=True)),
                ('lieu_dit', models.CharField(blank=True, max_length=200, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('localite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Localite')),
            ],
        ),
        migrations.CreateModel(
            name='SuiviLoyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField()),
                ('etat_suivi', models.CharField(choices=[('A_VERIFIER', 'A vérifier'), ('IMPAYE', 'Impayé'), ('EN_RETARD', 'En retard'), ('PAYE', 'Payé'), ('SURPAYE', 'Surpayé')], default='A_VERIFIER', max_length=10)),
                ('remarque', models.TextField(blank=True, null=True)),
                ('loyer_percu', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('charges_percu', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_paiement_reel', models.DateField(blank=True, null=True)),
                ('financement_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.FinancementLocation')),
            ],
            options={
                'ordering': ['date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='TypeSociete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='societe',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.TypeSociete'),
        ),
        migrations.AddField(
            model_name='professionnel',
            name='societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Societe'),
        ),
        migrations.AddField(
            model_name='personne',
            name='societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Societe'),
        ),
        migrations.AddField(
            model_name='personne',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='locataire',
            name='personne',
            field=models.ForeignKey(error_messages={'unique': 'Please enter your name'}, on_delete=django.db.models.deletion.CASCADE, to='main.Personne'),
        ),
        migrations.AddField(
            model_name='locataire',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Fonction'),
        ),
        migrations.AddField(
            model_name='locataire',
            name='societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Societe'),
        ),
        migrations.AddField(
            model_name='localite',
            name='pays',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Pays'),
        ),
        migrations.AlterUniqueTogether(
            name='indicesante',
            unique_together=set([('date_calcul', 'annee_base')]),
        ),
        migrations.AddField(
            model_name='fraismaintenance',
            name='entrepreneur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Professionnel'),
        ),
        migrations.AddField(
            model_name='fraismaintenance',
            name='societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Societe'),
        ),
        migrations.AddField(
            model_name='financementlocation',
            name='indice_sante',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.IndiceSante'),
        ),
        migrations.AddField(
            model_name='contratlocation',
            name='indice_sante_base',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.IndiceSante'),
        ),
        migrations.AddField(
            model_name='contratgestion',
            name='gestionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Personne'),
        ),
        migrations.AddField(
            model_name='batiment',
            name='localite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Localite'),
        ),
        migrations.AddField(
            model_name='alerte',
            name='contrat_gestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ContratGestion', verbose_name='Contrat de gestion'),
        ),
        migrations.AddField(
            model_name='alerte',
            name='contrat_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ContratLocation', verbose_name='Contrat location'),
        ),
        migrations.AlterUniqueTogether(
            name='proprietaire',
            unique_together=set([('proprietaire', 'batiment')]),
        ),
        migrations.AlterUniqueTogether(
            name='personne',
            unique_together=set([('nom', 'prenom', 'prenom2')]),
        ),
        migrations.AlterUniqueTogether(
            name='locataire',
            unique_together=set([('personne', 'contrat_location')]),
        ),
    ]
