# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-01-19 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batiment',
            name='performance_energetique',
            field=models.CharField(blank=True, choices=[('A <= 50 kwh/m².an', 'A <= 50 kwh/m².an'), ('B 51>= <90 kwh/m².an', 'B 51>= <90 kwh/m².an'), ('C 91>= <150 kwh/m².an', 'C 91>= <150 kwh/m².an'), ('D 151>= <230 kwh/m².an', 'D 151>= <230 kwh/m².an'), ('E 231>= <330 kwh/m².an', 'E 231>= <330 kwh/m².an'), ('F 331>= <450 kwh/m².an', 'F 331>= <450 kwh/m².an'), ('G >450 kwh/m².an', 'G >450 kwh/m².an')], default=None, max_length=30, null=True),
        ),
    ]
