# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fonction', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Professionnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Fonction')),
            ],
        ),
        migrations.CreateModel(
            name='TypeSociete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='alerte',
            old_name='contratGestion',
            new_name='contrat_gestion',
        ),
        migrations.RenameField(
            model_name='alerte',
            old_name='contratLocation',
            new_name='contrat_location',
        ),
        migrations.RemoveField(
            model_name='societe',
            name='personnel',
        ),
        migrations.AddField(
            model_name='fraismaintenance',
            name='contrat_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ContratLocation'),
        ),
        migrations.AddField(
            model_name='personne',
            name='num_compte_banque',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='personne',
            name='personne_type',
            field=models.CharField(blank=True, choices=[('NON_PRECISE', '-'), ('LOCATAIRE', 'Locataire'), ('PROFESSIONNEL', 'Professionnel'), ('PROPRIETAIRE', 'Propriétaire'), ('ANCIEN_LOCATAIRE', 'Ancien locataire'), ('ANCIEN_PROPRIETAIRE', 'Ancien propriétaire')], default='NON_PRECISE', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personne',
            name='societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Societe'),
        ),
        migrations.AddField(
            model_name='suiviloyer',
            name='date_paiement_reel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batiment',
            name='performance_energetique',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='batiment',
            name='superficie',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='fraismaintenance',
            name='batiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Batiment', verbose_name='Batiment'),
        ),
        migrations.AlterField(
            model_name='fraismaintenance',
            name='entrepreneur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Professionnel'),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='civilite',
            field=models.CharField(choices=[('NON_PRECISE', '-'), ('MADAME', 'Madame'), ('MADEMOISELLE', 'Mademoiselle'), ('MONSIEUR', 'Monsieur'), ('MAITRE', 'Maitre'), ('DOCTEUR', 'Docteur')], default='NON_PRECISE', max_length=15),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Fonction'),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Societe'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='localite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Localite'),
        ),
        migrations.AddField(
            model_name='professionnel',
            name='personne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Personne'),
        ),
        migrations.AddField(
            model_name='professionnel',
            name='societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Societe'),
        ),
        migrations.AddField(
            model_name='societe',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.TypeSociete'),
        ),
    ]
