# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170320_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeledocument',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
