# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_modeledocument_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeledocument',
            name='fichier_modele',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
