# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_modeledocument_fichier_modele'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionnel',
            name='actif',
            field=models.BooleanField(default=False),
        ),
    ]
