# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170509_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='prenom2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='personne',
            unique_together=set([('nom', 'prenom', 'prenom2')]),
        ),
    ]
