# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170512_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndiceSante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_calcul', models.DateField()),
                ('annee_base', models.IntegerField()),
                ('indice', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
    ]
