# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20170522_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='fonction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Fonction'),
        ),
        migrations.AlterField(
            model_name='professionnel',
            name='actif',
            field=models.BooleanField(default=True),
        ),
    ]
