# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20170602_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='personne_type',
        ),
    ]
