# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_personne_personne_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='localite',
            name='pays',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Pays'),
        ),
    ]
