# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_localite_pays'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeledocument',
            name='modele',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
