# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 09:41
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_modeledocument_modele'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentModele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('contenu', ckeditor.fields.RichTextField()),
                ('sujet', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='modeledocument',
            name='modele',
        ),
    ]
