# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-20 19:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20180122_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suiviloyer',
            name='charges_percu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='suiviloyer',
            name='loyer_percu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
